_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": gradients/mapper.fc4.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu4.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu3.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_hce_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu6.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc4.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu4.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/mapping_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu4.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc4.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu5.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu6.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_l2_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu5.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_tji_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc4.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu4.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu3.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu5.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu6.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/inverting_l2_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu1.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_pt_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_tji_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc4.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu6.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu3.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu1.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_pt_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/mapping_l2_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc6.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu5.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc5.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu6.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_hce_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu5.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu4.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc3.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu5.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.prelu2.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc5.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/inverting_l1_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu2.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu4.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc4.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc6.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.prelu6.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/inverting_l2_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mapping_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc2.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc1.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/inverter.fc4.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/mapper.fc2.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 1
                - 7
                - 13
                - 23
                - 55
                - 62
                - 66
            "4": 3.12.9
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-x86_64
b1_i:
    value: 0.5
b1_m:
    value: 0.5
b2_i:
    value: 0.999
b2_m:
    value: 0.999
batch_size:
    value: 24
lr_i:
    value: 0.0002
lr_m:
    value: 0.0002
num_epochs:
    value: 50
